name: Production Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0, v2.3.1

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      # - name: Debug workspace
      #   run: |
      #     echo "Current directory: $PWD"
      #     ls -lh
      #     ls -lh ${{ github.workspace }}
      #     cat ${{ github.workspace }}/pyproject.toml

      - name: Build package
        run: |
          python -m build --sdist --wheel
          ls -lh dist/


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}